##### CLEANUP
# Unbind the default tmux command prefix, CTRL+b.
unbind C-b
#####

##### PREFERENCES
# Use CTRL+a as our tmux command prefix.
set-option -g prefix C-a

# don't rename windows automatically
set-option -g allow-rename off

##### MAPPINGS
# PREFIX CTRL+a: send CTRL+a to the local application.
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# PREFIX r: Instantly reload tmux's configuration file.
bind r source-file ~/.tmux.conf \; display "tmux has been reloaded!"

#### Look
#  modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=colour1 bg=colour18 bold'

# statusbar
set -g status-bg black #base02
set -g status-fg yellow #yellow
set -g status-attr default
